#! /usr/bin/env python
# encoding: utf-8

# waf build file

def set_options(opt):
    pass

def configure(conf):
    pass

def build(bld):
    application_name = "video_input"

    print("Building " + application_name)

    source_files = bld.glob("*.cpp")
    #source_files = "video_input.cpp" #bld.glob("*.cpp")
    print(source_files)

    #libs = ["BOOST_PROGRAM_OPTIONS",]
    libs = ["boost_program_options", ]

    task = bld.new_task_gen(
        features = 'cxx cprogram',
        source = source_files,
        target = application_name,
        lib = libs,
        includes = "../../",
        uselib_local=["AbstractApplication", "uniclop_devices"]
        )
