#! /usr/bin/env python
# encoding: utf-8

# waf build file

def set_options(opt):
    pass

def configure(conf):
    
    conf.check_cfg(package='gtk+-2.0', uselib_store='GTK', atleast_version='2.14.0', mandatory=True)
    conf.check_cfg(package='gstreamer-0.10', uselib_store='GSTREAMER', atleast_version='0.10.20', mandatory=True)

    return
    
def build(bld):
    application_name = "video_input"

    print("Building " + application_name)

    source_files = bld.glob("*.cpp")
    #source_files = "video_input.cpp" #bld.glob("*.cpp")
    print(source_files)

    #libs = ["BOOST_PROGRAM_OPTIONS",]
    libs = ["boost_program_options", ]

    task = bld.new_task_gen(
        features = 'cxx cprogram',
        source = source_files,
        target = application_name,
        lib = libs,
        include = "../../",
        #uselib="GTK GSTREAMER",
        uselib_local=["AbstractApplication", "uniclop_devices"]
        )
