#! /usr/bin/env python
# encoding: utf-8

# waf build file

def set_options(opt):
    pass

def configure(conf):
    pass

def build(bld):

    print("Building uniclop_devices")

    source_files = bld.glob("*/*.cpp")
    print(source_files)

    task = bld.new_task_gen(
        #features = 'cxx cstaticlib',
        features = 'cxx cshlib',
        source = source_files,
        name = "uniclop_devices",
        target = "uniclop_devices",
        libs = ["boost_thread", "jpeg", "png", "avcodec", "avformat", "cv", "cvaux", "highgui", "cxcore", "Xext", "Xrandr"],
        includes = "../../",
        )
